[package]
name = "ergo-lib-wasm"
version = "0.20.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "WASM bindings for ergo-lib"
repository = "https://github.com/ergoplatform/sigma-rust"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
rest = ["ergo-lib/rest"]

[dependencies]
base16 = "0.2.1"
serde = { version = "1.0", features = ["derive"]}
ergo-lib = { version = "^0.20.0", path = "../../ergo-lib"}
sigma-util = { version = "^0.8.0", path = "../../sigma-util"}
serde_json = "1.0"
js-sys = "0.3"
web-sys = {version = "0.3", features = ["Url"]}
url = "2.2"
bounded-integer = { version = "^0.5", features = ["types"] }
futures = "0.3"
thiserror = "1"

# used in elliptic-curve(in ergo-lib), compiled here with WASM support
getrandom = {version = "0.2.7", features = ["js"]}

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

derive_more = "0.99"
num-traits = "0.2.14"

[dependencies.serde_with]
version = "1.9.1"
features = [ "json" ]

[dependencies.wasm-bindgen]
version = "0.2.79"
features = ["serde-serialize"]

[dependencies.wasm-bindgen-futures]
version = "0.4.28"

[dependencies.bounded-vec]
version = "^0.7.0"
features = ["serde"]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
ergo-lib = { version = "^0.20.0", path = "../../ergo-lib", features = ["arbitrary"] }

[dev-dependencies.proptest]
# wasm support, via https://altsysrq.github.io/proptest-book/proptest/wasm.html
version = "1.0.0"
# The default feature set includes things like process forking which are not
# supported in Web Assembly.
default-features = false
# Enable using the `std` crate.
features = ["std"]

[package.metadata.wasm-pack.profile.release]
# wasm-opt = ["-O", "--enable-mutable-globals"]
wasm-opt = false
